version: '3.8'

services:
  vod-node-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CLOUDFRONT_URL=${CLOUDFRONT_URL}
      - CLOUDFRONT_PRIVATE_KEY=${CLOUDFRONT_PRIVATE_KEY}
      - CLOUDFRONT_KEY_PAIR_ID=${CLOUDFRONT_KEY_PAIR_ID}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - BUCKET_REGION=${BUCKET_REGION}
      - BUCKET_NAME=${BUCKET_NAME}
      - DB_MASTER_USER=${DB_MASTER_USER}
      - DB_MASTER_PASSWORD=${DB_MASTER_PASSWORD}
      - DB_ENDPOINT=${DB_ENDPOINT}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_PROVIDER=${DB_PROVIDER}
      - DB_URL=${DB_URL}
    volumes:
      - .:/app
      - /app/node_modules
